### PR TITLE
Assets and configuration providers

### LINKED ISSUE #18: Launching doesn't make a new build?
3.3.2 stable mono oficial

**OS/device including version:**

win10  64

**Issue description:**

I am using "launch" but a new version is not created with my new code.
It seems that launching does not recompile the game and execute this new version, am I wrong?

**Screenshots of issue:**

### LINKED ISSUE #23: Running from vscode doesn't work
`To configure a project for debugging open the Godot project folder in VS Code. Go to the Run tab and click on create a launch.json file. Select C# Godot from the dropdown menu. Now, when you start the debugger in VS Code your Godot project will run.`

This is from the official website however there is no option of "C# Godot" in launch.json options. Everything else works ok.

### LINKED ISSUE #29: Incompatible with recent VSC Version
Win10 64bit / Godot_v3.3.4-stable_mono_win64 / VSC  1.60.2 / C# Tools for Godot 0.1.3 / .Net 5.0

Apparent Issue: No launch.json can be generated. When starting launch.json generation in debug pane, no "C# Godot" option is provided. Starting project in Godot works as long as "waiting for debugger" is disabled. When "waiting for debugger" is enabled, game will crash with a timeout. 

Steps to reproduce: 
- Use versions as above. 
- Start new project in godot
- Create scene with root node. Attach C# Script. VSC starts, project is generated. 
- Try to generate launch.json. Does not work

It seems that in package.json -> contributes->debuggers->"enableBreakpointsFor" is no longer supported as when the package.json is opened it will be flagged as not allowed
"Property enableBreakpointsFor is not allowed."   -> https://code.visualstudio.com/updates/v1_42

Maybe the cause or not. 
Seems that raulsntos Pull Request #22  also corrects this. 

Unfortunately I was not able to build the extension myself so I cannot test it that really fixes this problem :-(

### LINKED ISSUE #30: All run and debug options are not working
**OS/device including version:**

Windows 10

**Issue description:**

Tried to use "Play in Editor", "Launch", and "Attach" which all options did not work at all.

### PR DESCRIPTION
**Pull request by raulsntos**
I think I might have gotten a little bit carried away and ended up doing too much, let me know if you want me to split this PR into separate smaller ones or if you want me drop something.

Basically, this PR refactors the extension a bit to try and have things more organized. Here are the biggest changes:

- Generate `tasks.json` and `launch.json`: Before it only generated the `launch.json` debug configuration, now it can also automatically generate a build task that is automatically set as the `preLaunchTask` for the Launch debug configuration (this fixes #18)
- Adds snippets for `launch.json`, this allows the user to add debug configuration to an existing `launch.json` file easily.
- Adds a command to manually generate the `tasks.json` and `launch.json` files for convenience (if the files already exists, the user will be asked to confirm overriding them).
- Configuration class which observes changes in the configuration, currently listening to the `mono-debug` configuration (since the extension uses their configuration for the exceptions) and this extension's custom configuration (the only one for now is an option to configure the path to the Godot executable to use it automatically when generating the `tasks.json` and `launch.json` files).
- If the user hasn't set the Godot executable path in the configuration it tries to find if the `godot` command is in the PATH (I have it in the PATH but I know it's unlikely many users do that), otherwise the user will have to manually introduce the path in the generated `tasks.json` and `launch.json` files like before.
- Also updates the `package.json` to replace the deprecated `debuggers.enableBreakpointsFor` with the new `breakpoints` option (closes #23, closes #29, closes #30).

If this PR gets merged I'm willing to also update the `README.md` to reflect these changes.

### CODE REVIEW

File: src/godot-utils.ts [hunk 1]
```diff
@@ -13,3 +15,27 @@ export function fixPathForGodot(path: string): string {
...
+    }
+
+    // Check if the godot command is in the path
+    path = await lookpath('godot');
+    if (path) {
+        return path;
+    }
+
+    // TODO: How to find the Godot executable?
+    // We could check common paths...
```
Comment (neikeq) [inline src/godot-utils.ts:37]: If the extension is connected to a running Godot editor instance, then it should be possible to get the Godot editor path from the metadata:

https://github.com/godotengine/godot-csharp-vscode/blob/3de6294befff33c5c5e3bf302a126b27c0927b1b/src/godot-tools-messaging/client.ts#L216
https://github.com/godotengine/godot-csharp-vscode/blob/3de6294befff33c5c5e3bf302a126b27c0927b1b/src/godot-tools-messaging/client.ts#L388

In fact, this function should always return that before anything else if `Configuration.Value.godotExecutablePath` is not set.

**Review by neikeq — APPROVED** [review]
Changes look good. There are conflicts that need to be fixed. The `vscode-tasks.d.ts` is fine if it cannot be referenced in any other way.

File: src/godot-utils.ts (hunk 1 above)
Comment (neikeq) [reply src/godot-utils.ts:37]: To be clear, I'm not requesting to implement this change in this PR. Just giving one of the answers to the question in the comment. It's probably a good idea to include this info in the comment, though.

File: typings/vscode-tasks.d.ts [hunk 2]
```diff
@@ -0,0 +1,353 @@
...
+        message: number;
+
+        /**
+         * Specifies if the last pattern in a multi line problem matcher should
+         * loop as long as it does match a line consequently. Only valid on the
+         * last problem pattern in a multi line problem matcher.
+         */
+        loop?: boolean;
+    }
+}
```
[the remark this answers is not in the document]
Comment (raulsntos) [reply typings/vscode-tasks.d.ts:353]: It's just the type information for tasks, unfortunately it does not seem to be provided by the `@types/vscode` package. It's taken from VSCode's documentation: https://code.visualstudio.com/docs/editor/tasks-appendix

I can get rid of it and replace the references with the `any` type (it's only used in [src/assets-generator/tasks.ts](https://github.com/raulsntos/godot-csharp-vscode/blob/task-provider/src/assets-generator/tasks.ts)) but I prefer using types when possible.

File: src/godot-utils.ts (hunk 1 above)
Comment (raulsntos) [reply src/godot-utils.ts]: Done

File: typings/vscode-tasks.d.ts (hunk 2 above)
[the remark this answers is not in the document]
Comment (neikeq) [reply typings/vscode-tasks.d.ts:353]: I think it's fine then

**Comment by neikeq** [comment]
Thanks for the huge work!
